name: (Scheduled) Docker Build and Push to Docker Hub

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load .env file
        run: |
          set -o allexport
          source .env
          set +o allexport
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
          echo "TORCH_VERSION=$TORCH_VERSION" >> $GITHUB_ENV
          echo "CUDA_VERSION=$CUDA_VERSION" >> $GITHUB_ENV
          echo "EXTRA_TAG=$EXTRA_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set image tag
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_HUB_USERNAME }}/$REPO_NAME:torch$TORCH_VERSION-$CUDA_VERSION$EXTRA_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            --build-arg TORCH_VERSION=$TORCH_VERSION \
            --build-arg CUDA_VERSION=$CUDA_VERSION \
            -t $IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: |
          docker push $IMAGE_TAG
